### ISSUE TITLE
Ability to change log level of FML logger

### ISSUE THREAD

**Issue by BubbaJames** [MinecraftForge/FML#175]
If this feature/ability already exists, please update FAQ with instructions.

Issue:
FML logger is logging at level ALL which produces files in the GBs.  Please provide an easy mechanism to set log level in config.

**Comment by cryptiklemur** [comment]
Hate to necro this super old issue, but how are we supposed to use our own logger? Havent seen any docs on this. Would love to log to my own file.

**Comment by ryantheleach** [comment]
FMLPreInitializationEvent::getModLog
