### ISSUE TITLE
fml.dumpRegistry Only dumps custom ItemStacks 

### ISSUE THREAD

**Issue by DillonJettCallis** [MinecraftForge/FML#375]
It should really dump the Block and Item registries too in order to be really useful.

I could write it myself and make a pull request if that's alright.

**Comment by Morketh** [comment]
I know this is an old issue. but i had a quick question about this little piece of code. I was digging around in my forge source for a mod I'm building and saw this feature and wanted to know how to use it i cant seem to find any documentation on it at all. What also looks like a config setting in the code on line 161: `if (Boolean.valueOf(System.getProperty("fml.dumpRegistry", "false")).booleanValue())` i cant seem to find that in any config file any where in the game directory structure.

**Comment by Cazzar** [comment]
Just look up how to use java properties, though that is more a question
that should be taken to the forums.

**Comment by Morketh** [comment]
not really looking to use Java properties id like to use the dumpRegistry() im sorry for the confusion i thought i was clear on that

**Comment by LexManos** [comment]
Set the system variable 'fml.dumpRegistry' to true.
Run java with -Dfml.dumpRegistry=true
