### ISSUE TITLE
Bungee can not connect to Forge in 1.7

### ISSUE THREAD

**Issue by mindforger** [MinecraftForge/FML#391]
I had a hybrid server on 1.6 with a bungeeproxy connecting a vanilla and a forge server.

Now in 1.7 this is not possible anymore, after asking in the Bungee Project:
https://github.com/SpigotMC/BungeeCord/issues/899
i got told:

"forge support was removed for 1.7 because of protocol changes.
if anyone is aware what forge changed in 1.7 protocol, maybe this can be added again" 

i don't know how "closed" you are on your stuff regarding this issue, but can't we all be friends and exchange some informations between tose two awesome projects to get it working again and furthermore keep it up for 1.8 and beyond? Currently most of my users suffer from this issue and play on vanilla or on my standalone forge server, but can not coommunicate with their other friends or visit them in just a blink.

Thank you,

mindforger

**Comment by wjhhuizi** [comment]
So, Could any one tell me IF BungeeCord support Cauldron 1.7.2 ??? Thanks!!!
