### ISSUE TITLE
Game often crashes in 1.8, even without mods.

### ISSUE THREAD

**Issue by Eternaldoom** [MinecraftForge/FML#543]
In my 1.8 dev environment, the game often crashes when I open a world, even with no mods. It crashes much less often on superflat worlds. [Here's](https://gist.github.com/Eternaldoom/4068eb43599df62c7fee) the crash report.

**Comment by linuxrules94** [comment]
It seems to be caused by asynchronous world saving. I can reproduce the error after playing in minecraft for a few minutes consistently with the `weather and tornadoes mod` (which has a world save feature)

**Comment by LexManos** [comment]
THe issue this was referring to has been fixed for a long long time.

**Comment by linuxrules94** [comment]
Yeah, definitely seems fixed.
