### ISSUE TITLE
IFuelHandler does not handle all cases

### ISSUE THREAD

**Issue by ScottKillen** [MinecraftForge/FML#559]
In `TileEntityFurnace`, the `getItemBurnTime(ItemStack)` method specifies the burn times of vanilla blocks before the call to `GameRegistry.getFuelValue(ItemStack)`.
- Because the vanilla code specifies that blocks made from wood (except vanilla wooden slabs) have a burn time of 300, custom wood slabs (and indeed all wood blocks) provided by mods are assigned a fuel value of 300 and the mod's registered IFuelHandler is never queried.
- Additionally, fuel values for vanilla blocks and items cannot be modified.

To fix this, I propose that the call to get `GaemRegistry.getFuelValue(ItemStack)` should be moved to the top of `TileEntityFunace.getItemBurnTime(ItemStack)`.

**Comment by ScottKillen** [comment]
I thought I would touch this to bring it to attention of @cpw now that he is back. If it is not a priority, so be it.

**Comment by liach** [comment]
yeah... finally, this is fixed by events.
