### ISSUE TITLE
100 or more logs causes game to not start (Also, why is FML generating 100+ logs?)

### ISSUE THREAD

**Issue by 1Matthias** [MinecraftForge/FML#582]
Hello! 
While playing last night, my game crashed. When I went to boot it back up, it posted these lines and stopped doing anything: http://pastebin.com/DL1ZZ7C7
I went away for a couple of minutes, thinking that it was slow to load, but came back to see the exact same screen. Ok, try booting up again. Same thing. Ok, reinstall FTB launcher. Nothing. Ok. Time to check the pack folder. I saw the I had logged in 100 times, and decided to try moving all 100 logs to my documents folder. It booted up first time.

**Comment by Cisien** [comment]
The log mentions 1.6.4, which I am fairly sure is no longer supported

**Comment by Kubuxu** [comment]
@Cisien it is still an issue in 1.7.10 and I think no-one touched this code while porting to 1.8.

**Comment by LexManos** [comment]
This is all controlled by log4j, it should only keep 3, deleting the rest at startup, if it doesnt it means that something is holding a reference to those log files and not letting it be deleted.

**Comment by 1Matthias** [comment]
Odd. Are there any mods that are known to cause this?

**Comment by LexManos** [comment]
None off hand, depends on your type of server there is usually a way to get the handle of everything locking the file.
You'd have to talk to your server admin and figure it out, this shouldn't be anything to do with Forge.

**Comment by 1Matthias** [comment]
Ok then, thank you for looking into this! :)

**Comment by OvermindDL1** [comment]
@1Matthias it is a bug in log4j, I hit it as well, forge could fix it but as the bug comes from MC itself doing things wrong then it will not be, just add something to your startup script to ferry the logs away like I do.

**Comment by LexManos** [comment]
If you know where the bug is feel free to send off a PR. We fix Vanilla bugs all the time

**Comment by OvermindDL1** [comment]
We spoke of it about a year ago give or take when I first started hitting it, you stated it will not be fixed even though I gave you the fix because the code was in Minecraft itself and not caused by Forge.  I do not recall what the fix is but if you check the IRC logs it would be there.  I have my workaround and have been using it since, since otherwise the game became unstartable.
