### ISSUE TITLE
GetEffectiveSide does not take into account netty threads

### ISSUE THREAD

**Issue by Tarig0** [MinecraftForge/FML#583]
GetEffectiveSide returns client when calling it from a netty thread

Possible Fix
https://github.com/SlimeVoid/SlimevoidLibrary/blob/28b76d7abe95671b70c511fcb17de48804341ff1/src/main/java/net/slimevoid/library/util/helpers/PacketHelper.java#L57-L63

This will return Server for the threads

Server thread
Netty Server IO \#0
Netty Server IO \#1...

**Comment by Lunatrius** [comment]
#578

**Comment by diesieben07** [comment]
Possible fix: Don't use `getEffectiveSide` at all... It's an ugly hack.

**Comment by LexManos** [comment]
-----^
