### ISSUE TITLE
Allow certain FML PlayerEvents to be cancellable

### ISSUE THREAD

**Issue by luacs1998** [MinecraftForge/FML#585]
I would like to request that the following FML PlayerEvents be made cancellable:

- ItemPickupEvent (on cancel, item is NOT picked up)
- ItemCraftedEvent (on cancel, craft is unsuccessful)
- ItemSmeltedEvent (on cancel, craft is unsuccessful)
- PlayerChangeDimensionEvent (on cancel, player is sent back to dimension he came from)

This would be especially useful for mods like ForgeEssentials which offer protection/worldguard-like systems.

Preventing players from picking up items is useful under certain scenarios. Some server admins may not want to allow the player to possess an item. By allowing item pickups to be cancelled, a protection-offering mod like FE can thus use permissions to control who can pick up and item and who cannot.

FE does not support permission-based restriction of crafting/smelting recipes. This change would allow me to properly cancel the event based on whether the player is allowed to craft the item, and thus properly support permission-based recipe banning.

Also, to prevent players changing dimension, FE currently uses a lot of hacks to send the player back to the source dimension. If PlayerChangeDimensionEvent is made cancellable, I can thus simply cancel the event and abort the teleportation. 

If possible I may make a PR, but I'll just leave this issue here first.

**Comment by LexManos** [comment]
You know the rules.
