### ISSUE TITLE
FML touches code it has no business of touching

### ISSUE THREAD

**Issue by peterix** [MinecraftForge/FML#593]
Example:
```
[FML]: =============================================================
[FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[FML]: Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[FML]: Use FMLCommonHandler.exitJava instead
[FML]: =============================================================
```
Full log: http://paste.ee/p/XblDm - crash there is unrelated though.

I don't think it does anything right now, because it's basically just exiting when an unrecoverable error happens before any of the Minecraft stuff loads at all.

Can you blacklist anything in *org.multimc* from being searched for mods or rewritten in any way? I would like to not be surprised by similar *future* rewrites that do have wrong side-effects.

**Comment by coolsquid** [comment]
There's no rewrite. FMLs security manager doesn't allow for silently exiting Java. FML isn't actually changing MultiMCs code.

**Comment by peterix** [comment]
That is a change oh behavior, right?

**Comment by coolsquid** [comment]
Not really. Whenever anything calls for System.exit(), Java sends a message to the system security manager. The security manager can then choose what to do.

**Comment by peterix** [comment]
I guess that's harmless enough.

**Comment by diesieben07** [comment]
Actually FML does transform System.exit calls. They will be intercepted and an exception will be thrown if they don't come from a list of trusted sources (namely Minecraft code).

**Comment by Kubuxu** [comment]
@peterix calls to System#exit are intercepted. Only change to behaviour is message being printed.

**Comment by LexManos** [comment]
The entire point is to capture WHY minecraft closes, it does not prevent minecraft from closing. So no. Its doing exactly what it should in the exact manner it should.

**Comment by peterix** [comment]
Ok. I will find a way to fix it outside FML.
