### ISSUE TITLE
1.8 Will not launch, Error loading language files

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/FML#600]
The recent update of forge to update FML has caused me to notice that minecraft no longer launches. I believe this has something to do with the recent language file changes to opt-in loading using normal java properties. Upon launching the game it crashes with this crash report. http://pastebin.com/TSx6rAnr

Edit #599 fixes this (Saw this after)

**Comment by modmuss50** [comment]
Im not sure if this is the same issue, but I am still getting this on 1311(new newest).

http://pastebin.com/QB6dd2sn
