### ISSUE TITLE
GameRegistry should have a method for texture registration

### ISSUE THREAD

**Issue by CAD97** [MinecraftForge/FML#603]
`net.minecraftforge.fml.common.registry.GameRegistry` should have a method for texture registration.

Currently, to register an item's texture, you have to use the below code:

```
Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(itemReference, itemMeta, new ModelResourceLocation("modID:itemName", "inventory"));
```

and for blocks, similarly:

```
Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(blockReference, blockMeta, new ModelResourceLocation("modID:blockName", "inventory"));
```

as well as include the necessary .json files.

I propose that, alongside the existing `GameRegistry.registerItem(Item, String)` and `GameRegistry.registerBlock(Block, String)` methods, a `GameRegistry.registerTexture(Item, int, String)` and `GameRegistry.registerTexture(Block, int, String)` be added to consolidate block/item registration back into the GameRegistry.

Code for this could be such:
```
/**
 * Register the specified item to use the specified .json rendering file(s).
 * 
 * @param item The item to register the texture for
 * @param meta The metadata for the item
 * @param resourceLocation The location of the .json render files, in the form "modID:itemName"
 */
public static Item registerTexture(Item item, int meta, String resourceLocation)
{
    Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, meta, new ModelResourceLocation(resourceLocation, "inventory");
    return item;
}

/**
 * Register the specified block to use the specified .json rendering files.
 * This is the same as calling registerTexture(Item.getItemFromBlock(block), meta, resourceLocation)
 *
 * @param block The block to register the texture for
 * @param meta The metadata for the block
 * @param resourceLocation The location of the .json render files, in the form "modID:itemName"
 */
public static Block registerTexture(Block block, int meta, String resourceLocation)
{
    registerTexture(Item.getItemFromBlock(block), meta, resourceLocation);
    return Block;
}
```

(I used `GameRegistry.registerItem` and `GameRegistry.registerBlock` as basis for format of JavaDoc)

**Comment by RainWarrior** [comment]
ModelLoader.setCustomModelResourceLocation does almost what you want. And it has the benefit of not needing to be called after the 1st resource loading, so you won't get any missing erros in the logs.

**Comment by CAD97** [comment]
Yep, that's pretty much what I what I thought was missing. Strange that none of the several dozen tutorials that I looked at trying to find the method that replaced the longer call mentioned anything other than the longer call. Apparently I need more Google-Fu and Library-digging-Fu.
Sorry to waste your time!

(Now to get it working, but I'm 99.9% sure the error is 100% on my side this time.)
