### ISSUE TITLE
Coremod transformers and EntityPlayer.

### ISSUE THREAD

**Issue by Dragon2488** [MinecraftForge/FML#605]
EntityPlayer and its subclasses are not transformed by a coremod transformers (More precisely, the first argument in the method of transformation is never equal net.minecraft.EntityPlayer or another class name extends EntityPlayer, apart from EntityPlayerMP).

**Comment by Dragon2488** [comment]
Hey, LexMacos, can you fix it?

**Comment by LexManos** [comment]
They are transformed just fine.

**Comment by Dragon2488** [comment]
No, they aren't. I tried something easy, like this:
![](http://i.imgur.com/oQtkkHR.png)
and get console output:
![](http://i.imgur.com/z77nYEu.png)
Oh, i forgot, my version is 1.7.10 (forge last build).

**Comment by LexManos** [comment]
Yes, they are if they wernt the game would crash for everyone because it could not deobfusicate the class. Something in your setup is broken and causing the classes the be defined before your transformer is.
Again, if you don't know how classloading works you should not be making a core mod.

**Comment by Dragon2488** [comment]
Yes, indeed, here and there was a challenge to the player.
Thanks you.
