### ISSUE TITLE
Lighting bolt with pig and villager

### ISSUE THREAD

**Issue by Azuxul** [MinecraftForge/FML#613]
Hi, i found a bug.
If pig struck by 3 lighting, 3 pig mean spawning.

More details in video :
<a href="http://www.youtube.com/watch?feature=player_embedded&v=jBQQsmuNZ30
" target="_blank"><img src="http://img.youtube.com/vi/jBQQsmuNZ30/0.jpg" </a>

Lighting dust code : https://github.com/Azuxul/MoreLight/blob/master/java/azuxul/morelight/items/LightingDust.java
https://github.com/Azuxul/MoreLight/blob/master/java/azuxul/morelight/items/AdvancedLightingDust.java

FML 1.8-11.14.1.1334

**Comment by LexManos** [comment]
This isn't a bug, this is a vanilla feature.
