### ISSUE TITLE
GuiUtils not using GlStateManager

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/FML#615]
In the GuiUtils class, OpenGL is called directly, and not through GlStateManager. This then becomes a problem when minecraft later tries to disable blend, causing the state manager to ignore the request, since it believes that blending already is disabled.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/38a85280de09ba8c08b7b2252b9839ebba015509
