### ISSUE TITLE
Substitution - IDs not being synced properly

### ISSUE THREAD

**Issue by master801** [MinecraftForge/FML#616]
Minecraft version: 1.7.10
FML and Forge version: 7.10.88.1307-1.7.10

Registering code: https://github.com/master801/betterAnvil-forge/blob/master/src/main/java/vdvman1/betterAnvil/BetterAnvil.java#L91

Client log when logging into a server: http://pastebin.com/vRDGTqBx

Some of its content were cut short due to Pastebin's size limit.
Note, this is purely only with FML, Forge and my custom build of a mod.

**Comment by cpw** [comment]
Without log files, it's very hard to comprehend what FML does here. It logs every action it takes, so my suggestion is to capture log files from an erroring session.

Unfortunately, there's a lot of mods that "think they know better" and directly futz with the registry, so it's possible this isn't FML, but rather hacky interference from something else.

But, please, log files are the start...

**Comment by cpw** [comment]
Also, please file a separate issue for the texture problem- I can't track both in one issue. Again, log files, and screenshots demonstrating what's going wrong, would be helpful here.

**Comment by master801** [comment]
Will do

**Comment by master801** [comment]
Log for FML and Forge version 7.10.88.1307-1.7.10: http://pastebin.com/vRDGTqBx

Some of its content were cut short due to Pastebin's size limit.

**Comment by cpw** [comment]
Thanks for the log file. It seems that your substitution isn't working properly. Can you explain the setup for the log file. Were you connecting to a dedicated server? It doesn't look like a single player game.

**Comment by master801** [comment]
Yes I was using a dedicated server. Should I try running on a lan server too?

**Comment by cpw** [comment]
OK. I'm going to try and recreate in a dedicated server environment. I thought I had this tested...

**Comment by master801** [comment]
Here's a download link to the mod I'm using, if you want.

http://www.mediafire.com/download/qs9uruagcn6n7uu/BetterAnvil-3.1.7-C.jar

**Comment by cpw** [comment]
One further request - have you tried moving your substitution to the PreInit event?

**Comment by master801** [comment]
Hmmm... that shouldn't matter, but I'll give it a go later.

**Comment by cpw** [comment]
It might - preinit comes before any assets are loaded, init comes after the first loading round..

**Comment by master801** [comment]
Alright, I tried moving the subsitution registration into pre-initialisation for both, and they both failed like before.

**Comment by cpw** [comment]
OK, for the anvil not working on a dedi server, try the new FML build above. I'll merge into forge shortly but this fixes my local test mod.

**Comment by master801** [comment]
Okay, I'll test that in a bit.

**Comment by cpw** [comment]
Forge #1342 should do the trick... If it does, I'll leave this issue until I merge the fix on the mainline, but enjoy ;) Update if you encounter further issues.

BTW: required-after:Forge@[10.13.2.1342,11] should force the right dependency.

Thanks for the issue report..

**Comment by master801** [comment]
Thank you for fixing it, cpw.

I'll reopen this issue if I have any problems with it.

**Comment by cpw** [comment]
Needs fixing in 1.8 as well..

**Comment by master801** [comment]
Sorry about that, forgot about 1.8...

Thank you cpw, for fixing it!
