### ISSUE TITLE
Subsitution - Textures not properly being registered

### ISSUE THREAD

**Issue by master801** [MinecraftForge/FML#618]
Minecraft version: 1.7.10
FML and Forge version: 7.10.88.1307-1.7.10

Registering code: https://github.com/master801/betterAnvil-forge/blob/master/src/main/java/vdvman1/betterAnvil/BetterAnvil.java#L91

Log: http://pastebin.com/NQGs1MDD

Some of its content were cut short due to Pastebin's size limit.
Note, this is purely only with FML, Forge and my custom build of a mod.

**Comment by cpw** [comment]
I think your anvil subtype needs to handle the icon registration.

**Comment by master801** [comment]
If I remember correctly, I tried that and the same error occured? I don't really know, I'll try that though.

**Comment by cpw** [comment]
I don't know that a super call is correct. You might have to copy the getIcon method, and probably the register method as well.

**Comment by master801** [comment]
Hmmm... I'll have to try that later then.
