### ISSUE TITLE
Kill LanguageRegistry, take two

### ISSUE THREAD

**Issue by Adaptivity** [MinecraftForge/FML#628]
LanguageRegistry was deprecated for removal in 1.8, FML now in 1.8 era, aren't it? Isn't it time to finally kill it?

**Comment by The-Fireplace** [comment]
It seems to me like it should be killed. It has been deprecated for long enough, and most mods have converted over. At this point, there are [plenty of easy to find tutorials](http://lmgtfy.com/?q=Minecraft+Forge+how+to+use+.lang+files) on how to set up the lang files.

**Comment by LexManos** [comment]
I'll kill it in the 1.9 update {I should remember it in my deprecation sweep}. UnIess there are MAJOR reasons not to.
Also This Repo is for archive purposes only don't make new things in here. {Github doesnt have a move :P}
