### ISSUE TITLE
Errors thrown during CONSTRUCTING phase put FML into bad state

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/FML#638]
edit: the proxy injector isn't always safe and so an exception from it can mask other errors..

An error thrown during this phase prevents all dependent mods from being loaded onto the classpath, yet they are reported as being loaded still, breaking facilities such as `@Optional` and causing all manner of chaos as mods have been sorted and are initializing with the assumption those mods are present. Not tested whether or not errors similarly occur for the mod that threw the error, or if it is only for dependencies.

Errors thrown during this phase should abort loading immediately, otherwise incorrect or irrelevant errors will be shown instead, prohibiting quickly identifying and fixing the problem.

**Comment by cpw** [comment]
In general mods should not access the constructing phase directly - this is an internal life cycle event.. Depending on it will break when the state engine is rewritten..

**Comment by skyboy** [comment]
Mods will always have access to the constructing phase though - this is when our constructors run.

**Comment by cpw** [comment]
Yes, but exceptions in the ctor are handled by FML. Directly handling the event in a coremod isn't protected..

**Comment by skyboy** [comment]
They're handled, but loading continues and other mods attempt to load - the other mods error out, as described above, which is the problem. Example: https://github.com/CoFH/CoFHCore/blob/059c456b710e356d03857405b7908ca86191f209/src/main/java/cofh/CoFHCore.java#L104-120

**Comment by cpw** [comment]
Yes, not sure how I can wrap error handling around it though, is my point - its all done inside the guava eventbus, and I don't get any clue the event failed to be handled properly.. I'll take another look at the event bus, but in general there is an expectation NOT to fuck up if you're doing it yourself in a coremod..

**Comment by skyboy** [comment]
That part of CoFHCore isn't handled by our core mod. That's the standard FML wrapper around `@Mod` classes. (`FMLCorePluginContainsFMLMod`)

**Comment by LexManos** [comment]
Logs.

**Comment by skyboy** [comment]
This is the log that happens when it works: https://gist.github.com/skyboy/9703364d4a3380c52803

However, if there are any mods present that soft-dep on the mods that hard-depend on CoFHCore, they will throw errors related to the dependency being reported as present, but the classes for those mods being unavailable. I have to generate that log, yet.

**Comment by cpw** [comment]
OK. The mod cofhcore did error, but the hard crash from eio masked the normal error handling. The problem I see in there is that the proxy injector isn't handling the cnfe properly, which IS in FML to fix..
