### ISSUE TITLE
The world xxxxxxxx (world) may have leaked: seen xx times; says "server shutting down" and then crashes/closing Minecraft

### ISSUE THREAD

**Issue by cocopuffs99** [MinecraftForge/FML#639]
With latest forge, gettting "Unexpected errorjava.lang.NullPointerException: Unexpected error at net.minecraft.client.renderer.ItemRenderer.func_78446_a
at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:962)

Here is the crash log: http://pastebin.com/PHT2GGU0
Hope that helps!
Thanks for FML it really is a great addition to MC =)

**Comment by LexManos** [comment]
Whatever block you are looking at is returning an invalid icon for it's texture.
Also this 1) has nothing to do with FML and 2) Doesn't match your title

**Comment by cocopuffs99** [comment]
So the invalid texture is causing my game to crash? I'm new to programming but I didnt think textures threw a crash in minecraft, wont it revert to the default texture or give a purple checkered block instead of crashing?  My issue is the crash and unable to load world

**Comment by cocopuffs99** [comment]
My title is the problem I am having and the bug message that comes up

**Comment by cocopuffs99** [comment]
The server shutdown on its own is the problem Im noticing

**Comment by LexManos** [comment]
If this is still an issue in Forge please recreate this in the Forge project, as FML is in it now. 
As for the issue itself, no you can still cause crashes if you send null textures around. the missing texture is for when things are being loaded and they are missing, not internal in your code.
