### ISSUE TITLE
Fluid Registry Crash

### ISSUE THREAD

**Issue by matthewsolc66** [MinecraftForge/FML#656]
I was creating a custom modpack, and I believe this error is the final one before I can play it.  It will load the title screen, but as soon as I go to load a pre-existing world or create a new one, it begins to load, and then crashes, and gives me the following crash report.

Crash Report
http://pastebin.com/L7mRhZmz

Log:
http://pastebin.com/zDUcmDC3

**Comment by LexManos** [comment]
You have a mod in your pack that is hacking its way into the fluid registry.
There is nothing we can do about this but crash your game because modders are being stupid.
Start removing mods until it stops happening and yell at whoever made the offending mod.

**Comment by matthewsolc66** [comment]
Thanks. I didn't really want to do that, so I spent another half hour google-ing different things trying to find the solution. And so apparenlty the problem was Minechem, so I went onto Jenkins and got the download from there, and that fixed it. It was either that or I downloaded the latest version of Forge. I was 3 versions behind.
