### ISSUE TITLE
Crash after world loads

### ISSUE THREAD

**Issue by matthewsolc66** [MinecraftForge/FML#657]
Before I had a fluid registry error, and now that the world loads, it crashes as soon as the world begins to generate terrain. It doesn't give me a crash report, so all I have is the log. This is a previously generated world, and it doesn't crash on new worlds. So if thats because of that, please let me know. I just am hoping that there is something that I can do to save my world.

LOG:
http://pastebin.com/414hNpZQ

**Comment by Bogdan-G** [comment]
`Couldn't look up profile properties for com.mojang.authlib.GameProfile...` 
Please update Optifine.

**Comment by matthewsolc66** [comment]
The fluid registry error was from a previous crash that I had already fixed. I just mentioned it because I thought it could be useful.

**Comment by Bogdan-G** [comment]
Pass this modpack authors and authors mods.

**Comment by matthewsolc66** [comment]
I am the modpack author
