### ISSUE TITLE
Make registerBlock find a MATCHING constructor

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/FML#658]
https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java#L204-L211

This code should instead look for a matching constructor. My constructor takes a Block and a Block, if I try to registerBlock with a Block and a BlockMyThing, it looks for a Block and a BlockMyThing and can't find a constructor so it throws an exception.

**Comment by diesieben07** [comment]
#509 #586 https://github.com/MinecraftForge/MinecraftForge/issues/1862

**Comment by cpw** [comment]
Closing. No new issues against FML please.

**Comment by coolsquid** [comment]
@cpw You can disable issues in the settings tab.

**Comment by liach** [comment]
He's a collaborator. soso.

**Comment by SoniEx2** [comment]
@cpw why not?

**Comment by LexManos** [comment]
Because the FML repo is deprecated/Archive only.
https://github.com/MinecraftForge/MinecraftForge/compare/1f679be553...cb6f92e3c7

**Comment by cpw** [comment]
Because it is no longer a separate project. Also, this issue is not valid. Finally, there's still pending issues open on FML so not disabling globally.
