### ISSUE TITLE
Some boilerplate license text refers to an incorrect GPL link

### ISSUE THREAD

**Issue by Glease** [MinecraftForge/FML#659]
Well, I'm just trying to lift some comments into my mod from fml, but I found something wrong:
You said fml is "available under the terms of the GNU Lesser Public License v2.1"
then you said "and is available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
I got confused by the url, then I followed it to page and found some GPLv2 thingy.
OMG, we got a problem. Those MIT, Apache, BSD guys shall got into prison then!( kidding) You need to fix these links ASAP (as I'm among those shall die)

**Comment by yuuka-miya** [comment]
Is this even valid?

**Comment by cpw** [comment]
@luacs1998 no, he's making up bullshit. FML is LGPL2.1 - this is the TEXT of the license. Commentary or anything else is subservient to this text: https://github.com/MinecraftForge/FML/blob/master/LICENSE-fml.txt

@Glease don't be a bloody fool and try and foment rage with this nonsense. I have no idea where you think I've ever said FML is gpl2.0. It has been LGPL 2.1 since it's inception in 2012.

**Comment by Glease** [comment]
@cpw please do take a look at the header of EACH SOURCE FILE instead of the license-fml.txt only.
Maybe I had just missed something important. Apologize for not mentioning them.
Also, if you told me "those doesn't count", well, I would accept being a fool, but I would be REALLY upset then.

**Comment by Glease** [comment]
@cpw please give me explanation about those confusing source file headers. Please take a look at the **URL**, too, not the **LICENSE NAME** only. I'll submit  a pull request to the "Forge proper" to fix this little bug.
Take a look at [this](https://github.com/MinecraftForge/MinecraftForge/pull/1873)

**Comment by cpw** [comment]
The text in each file is boilerplate copied directly from the licence site at the time of creation. If the boilerplate is wrong, I really don't care. I'm not gonna accept a PR modifying thousands of files.
