### ISSUE TITLE
Changelog for 10.13.3.1406 is huge (and probably incorrect)

### ISSUE THREAD

**Issue by erkro1** [MinecraftForge/FML#660]
Title says the most, go to: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1407-1.7.10/forge-1.7.10-10.13.3.1407-1.7.10-changelog.txt

The changelog for 1406 is giant and even includes changes like 'Update to MC 1.4.2', which is probably older changelog data added incorrectly.

I know it's pretty minor but I thought I would notify you guys on it.

**Comment by yuuka-miya** [comment]
1) I believe cpw doesn't want new issues opened here, open them on the forge repo instead.

2) Also, it could be something related to the FG changelog task, which IIRC simply scoops the latest commits, and puts them in the changelog. It probably picked up the FML merge in this way

**Comment by cpw** [comment]
Yup to both luacs.

**Comment by LexManos** [comment]
It is actually generated from Jenkins build changes. Jenkins detected the merge and decided to list all the commits that had been added. Which is a good thing.
However, yes it looks like crap.
So i've gone through and trimmed it down to a single line:
Merged FML into Forge's repo. FML is no longer developed separately.
Future builds should have cleaner change logs.
Note to OM/cpw: /jobs/minecraftforge/builds/{1405|1406}/changelog.xml.backup for the original xmls.
