### ISSUE TITLE
Error going full screen

### ISSUE THREAD

**Issue by jjmcquaid** [MinecraftForge/FML#662]
Okay, so I'm running Minecraft 1.7.10 and I do have fastcraft on MultiMC 0.4.6. And for some reason with the newer versions of Forge (the ones with the graphical loader thing. which I think is awesome btw). The game loads all the way through the graphic loader and then freezes on a maximized white screen. I thought this was a MultiMC issue. So I reported it there. https://github.com/MultiMC/MultiMC5/issues/998. Here's the server log https://gist.github.com/jjmcquaid/18d470e5cff947953f15. And here's the fml-client-latest log http://filebin.ca/22g9BsCCwEyH/fml-client-latest.log. Also starting Minecraft without the fullscreen option saved and then turning it fullscreen after, it loads it runs perfectly fine. It's only when it tries to start full screen, and it's only with the newer Forge versions with the graphic loader. Here's the error I get that seems to be the root of the problem. 

[23:16:36] [Client thread/ERROR]: Couldn't toggle fullscreen
java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-9,5,main] already has the context current

**Comment by peterix** [comment]
Also happens without fastcraft... without any mods at all.

**Comment by LexManos** [comment]
get us a log 'without any mods at all'

**Comment by jjmcquaid** [comment]
I can't reproduce the issue without the mods I have installed, I just don't know which one is causing it. That's all peterix.

**Comment by LexManos** [comment]
Also are you trying to go full screen WHILE the loading is happening? If so that is bad, we'll have to disable that.

**Comment by jjmcquaid** [comment]
No, it's only when the loading is complete and the client goes to full screen itself. If I change it to not go full screen in the options file in the minecraft folder, it runs fine. As well as if I press F11 or full screen it through the settings once it loads to the title screen. It only happens when it tries to full screen itself after the new graphic loading thing completes.
