### ISSUE TITLE
The old registerBlockHandler(...) method is still needed ! (an IBakedModel can't render every shapes)

### ISSUE THREAD

**Issue by Zyfarok** [MinecraftForge/FML#666]
For some shapes (like a prism with a triangular base, like in the carpentersblock mod), you can't render it with the new "IBakedModel".
And using a "TileEntitySpecialRenderer" (with the bindTileEntitySpecialRenderer(...) method) has two disadvantages : 
- You need a TileEntity (Not really worth if you don't need to store information inside)
- The TileEntity will not render at more than a certain distance. (Like signs and chests)

So please get the registerBlockHandler(...) method back ! =)
P.S.: I'm French so please be kind with my English.

**Comment by diesieben07** [comment]
Uhm... Why can't you use `IBakedModel`? Because there are triangles? That's not true, you can render any shape with `IBakedModel`.

**Comment by Zyfarok** [comment]
Any shape ? Sure ? Can you show me how ?

**Comment by Zyfarok** [comment]
I did just check "IBakedModel" code, and I don't see any method who allow us to render triangles...
IBakedModel does offer :
- getFaceQuads => (Obviously for Quads)
- getGeneralQuads => (same)
- boolean isAmbientOcclusion() => for occlusion...
- boolean isGui3d() => to say if the item in the inventory is 3D rendered
- boolean isBuiltInRenderer() => to say if the item as a custom render (different from the block)
- TextureAtlasSprite getTexture() => To get some kind of Texture...
- @Deprecated ItemCameraTransforms getItemCameraTransforms() => Deprecated so I don't care

So were are the triangles ?

P.S.: Hoho... it's the issue n°666...

**Comment by LexManos** [comment]
A triangle is a quad just with one corner repeated.
Beyond that FML is archive only.
We will not be giving back direct GL access. Nobody has yet to provide a valid reason why. This one is not.
