### ISSUE TITLE
No FML Handshake anymore?

### ISSUE THREAD

**Issue by chaos234** [MinecraftForge/FML#669]
Hey,

want to know if there is any Handshake done if a ProxiedPlayer (Bungee) conntects trough the ServerConnectedEvent or if it's gone away actually.

This event was able to send the info that the client uses forge and also what mods (incl. version) are loaded.

Is this no longer possible? And if so, will it be reimplemented?

**Comment by LexManos** [comment]
It is still possible bungeecord just needs to start the handshake again, we even added packets specifically designed for them to restart it. And remember THIS IS A DEAD REPO FML MERGED WITH FORGE!

**Comment by chaos234** [comment]
Oh, sorry for that but can you give me the neede code snipet please? I tried many things out but I duno how to start the handshake again.

It will be glad if you can help me _hope so_

In addition, we are using bungeecord with spigot but without forge.
