### ISSUE TITLE
DefaultArtifactVersion toString StackOverflow

### ISSUE THREAD

**Issue by Nerdpie** [MinecraftForge/FML#670]
Encountered in a recent [build of Tails](https://github.com/kihira/Tails/blob/ecf9f465aed0952609a4b2b9157c8097010b0e43/src/main/java/kihira/tails/common/Tails.java#L85); reported on Tails' [side](https://github.com/kihira/Tails/issues/55).

**Comment by heldplayer** [comment]
This does not belong here.

**Comment by Nerdpie** [comment]
How so?  The StackOverflow is caused when toString is called on an instance of DefaultArtifactVersion.  I merely referenced Tails to provide an example of when the issue is encountered.

**Comment by Lunatrius** [comment]
>  (Archive Only: Merged into [Forge](https://github.com/MinecraftForge/MinecraftForge) proper) The Forge Mod Loader - an opensource replacement mod loader for minecraft

**Comment by Nerdpie** [comment]
Ah.  My mistake then.  What's the proper way to go about 'moving' this to the Forge issue tracker then?  Just close and repost?

**Comment by AbrarSyed** [comment]
probably.. might be a good idea to include a link to this issue too

**Comment by Nerdpie** [comment]
Alright; will do.  Thanks.

**Comment by heldplayer** [comment]
Yeah, my apologies, I should have clarified that, sorry :S

**Comment by Nerdpie** [comment]
@heldplayer No worries; I felt rather silly after it was clarified.  Not entirely sure how I overlooked that, honestly...
