### ISSUE TITLE
Unable to change logoTexture without changing Forge or MC jar files

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/FML#675]
The splash.properties file provide options to change the logoTexture.
From what I could try, the related file can only be read from the Minecraft.jar or modpack.jar.
Changing resourcePackPath has no visible effect whatsoever.
I can't find any example or documentation about this.
This was tested with 7.99.39.1566-1.7.10.

**Comment by jeffreykog** [comment]
> Archive Only, Merged into forge proper

Please read before you post an issue. Open this issue on forge
