### ISSUE TITLE
can't open mod

### ISSUE THREAD

**Issue by blobr123** [MinecraftForge/FML#676]
i have pixelmon 4.1.3 installed, and in the mod folder, but i can't open it with forge, as it's not recognized. Do I need the launcher for pixelmon?

**Comment by AEnterprise** [comment]
this is a dead repo, FML has been merged into forge so issues should be opened there not here
this is also a question to be asked on the forums, not a bug tracker

and yes, you need to launch MC with the laucher and forge installed to be able to play with a mod, it's a minecraft mod, not a standalone game
