### ISSUE TITLE
Minecraft Forge Mod Loading Issue

### ISSUE THREAD

**Issue by Craftion424** [MinecraftForge/FML#678]
I installed the correct MC Forge version, ran the version once and installed the mod. Yet the mod isn't showing up in game! Please help! I moved the .jar file to the mod folder in my .minecraft folder but it's not loading in my game. Whenever I go to my Mod Options it doesn't show up!

**Comment by diesieben07** [comment]
Please post issues like this (with log files and proper information) on the [forum](www.minecraftforge.net/).
