### ISSUE TITLE
Internal Exception 

### ISSUE THREAD

**Issue by MKnance** [MinecraftForge/FML#681]
internal exception java.lang.classcastexception net.minecraftforge.fml.common.network.handshake.fmlhandshakemessage$HandshakeAck cannot be cast to net.minecraftforge.fml.common.network.handshake.fmlhandshakemessage$registrydata

error pops up when someone tried to log into my modded server with hamachi since the server is setup to use hamachi and this popped up on there side i can get in fine they cannot they get this error if you know anything about it please give reply or if this is an error thats been fixed in the half star version please let me know I am currently using minecraft forge 12.18.2.2097

**Comment by diesieben07** [comment]
This repository is no longer active, and moreover the github issues are not for general "please help me" posts.
